### ISSUE TITLE
Add GitHub plugin logo

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-github#1]
Logos on GitHub: https://github.com/logos
Optimized SVG logo: [octocat.zip](https://github.com/consulo/consulo-github/files/7474579/octocat.zip)
![изображение](https://user-images.githubusercontent.com/16825982/140309830-8c65d79d-9211-4f3c-9df8-78dc875375bd.png)

**Comment by VISTALL** [comment]
Think better use icon without small details.

**Comment by unv-unv** [comment]
The problem with black-and-transparent logo would be when it is displayed in Darcula theme. It would become almost invisible :(

**Comment by VISTALL** [comment]
IDEA in this case has second icon with prefix dark for dark themes. Currently Consulo not support this pattern. Maybe time is come:)

**Comment by unv-unv** [comment]
Velocity icon is also not looking good in Darcula theme.

**Comment by VISTALL** [comment]
I will add icons from JB repo, but support for dark icons required (https://github.com/JetBrains/intellij-community/tree/master/plugins/github/resources/META-INF)
